### ISSUE TITLE
Feature: Plugins

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#1]
Iocage implements a mechanism to automatically install jails from a template called "plugin". Various plugins are listed in the [freenas plugin registry](https://github.com/freenas/iocage-ix-plugins).

The way of installing packages and applying post-install hooks can be abstracted as discussed in https://github.com/iocage/iocage/issues/163 about Ansible (or other provisioning tools) integration. Running a hook script read from a GitHub source would be sufficient to support the current plugin system.

**Comment by gronke** [comment]
Does anybody use the CLI for installing such plugins or is it a feature only used by FreeNAS and does not need to be reflected in the command line interface. I'm asking because an interface change to just provide a post-install hooks for ix-plugins, ansible-playbooks, etc would allow us to come up with a much simpler interface. For example:

```
iocage set exec_poststart="plugin:///https://github.com/freenas/iocage-plugin-example"
```

or

```
iocage set exec_poststart="ansible:///https://github.com/gronke/my-ansible-playbook"
```

**Comment by skarekrow** [comment]
It's used currently in TrueOS and demonstrations to clients on FreeBSD machines, so preferably the CLI sticks around.
