### ISSUE TITLE
ezjail migration

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#109]
Previous versions of iocage provided a way to migrate jails from ezjail. Do we have ezjail users among us that can help with suggestions how to address this task?

Of course migration should work in both directions.

**Comment by skarekrow** [comment]
We actually didn't provide this. It was just a wiki article contributed to us.  But it could be useful.

**Comment by igalic** [comment]
"why document something you can automate" — probably not me, but someone way smarter

**Comment by gronke** [comment]
As discussed offline ezjail migration is no current aim of this project.

**Comment by yonk42** [comment]
here a hint for people migrating their jails:
use a fresh basejail and use this command to migrate the data
` rsync -av /usr/jails/xxxxx/ /iocage/jails/xxxxxx/root/  --exclude=/bin --exclude=/boot  --exclude=/basejail --exclude=/usr/lib32 --exclude=/usr/libdata --exclude=/usr/share --exclude=/usr/sbin --exclude=/usr/libexec --exclude=/usr/lib --exclude=/lib --exclude=/libexec --exclude=/usr/include --exclude=/rescue --exclude=/sbin --exclude=/usr/bin `

**Comment by igalic** [comment]
we might wanna document this in a tutorial…

**Comment by gronke** [comment]
@foo2342 We 😻PRs. I'd like to see this feature, but I'm unsure how the integration could look like. Maybe just a gist referenced in the documentation (like suggested by @igalic) works best because I do not see the knowledge about ezjail belong to libiocage or the `ioc` CLI command.
