### ISSUE TITLE
analyse libiocage code for security sensitive issues

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#111]
being a security-sensitive project, we should consider _automatically_ auditing our code for potential security issues.
being a security conscious project, i suggest we _"simply"_ add [bandit](https://pypi.python.org/pypi/bandit) to our travis tests.

**Comment by igalic** [comment]
i've tested the current master branch with

```
bandit --exclude iocage/tests/ -r .
```

and it looks quite _okay_
two of the high-severity issues are false-positives, since we're on Python 3.x.
The rest should be easy to clean up.

**Comment by gronke** [comment]
Is there a way to integrate this kind of check in our build system?

**Comment by igalic** [comment]
same as with mypy and flake8:

```diff
diff --git a/.travis.yml b/.travis.yml
index a45dc69..61e1dc6 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,6 +5,7 @@ sudo: false
 env:
   - MYPYPATH="$TRAVIS_BUILD_DIR/.travis/mypy-stubs"
 install:
-  - pip3 install flake8-mutable flake8-builtins flake8-mypy
+  - pip3 install flake8-mutable flake8-builtins flake8-mypy bandit
 script:
   - flake8 --exclude=__init__.py --ignore=E203,W391
+  - bandit --exclude iocage/tests/ -r .
diff --git a/requirements-dev.txt b/requirements-dev.txt
index 1917390..013ad27 100644
--- a/requirements-dev.txt
+++ b/requirements-dev.txt
@@ -2,5 +2,8 @@ pytest
 pytest-cov
 pytest-pep8
 pytest-mock
-mypy
+flake8-mutable
+flake8-builtins
+flake8-mypy
+bandit
 git+https://github.com/freenas/py-libzfs.git#egg=libzfs
```

**Comment by gronke** [comment]
Bandit was embedded in the build system with PR #112
