### ISSUE TITLE
Documentation of Code Analysis stages

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#115]
During the development of this project we introduced ned code analysis tools and utilized for quality assurance in our automated build system.

To make it easy for contributor to know and meet the requirements, we need to document the used tools and explain what is tested and how to run it on a local system.

As @araujobsd [pointed out](https://github.com/iocage/libiocage/pull/112#issuecomment-330846361) this can mitigate frustration of future contributors.

It can be helpful to split various checks on Travis CI into multiple smaller ones, so that we can show the individual status among the pull-request. See also: https://developer.github.com/v3/repos/statuses/

**Comment by araujobsd** [comment]
Perfect and very good initiative!

**Comment by igalic** [comment]
@araujobsd ^ how's this for a start?

**Comment by araujobsd** [comment]
Yeah, looks great! And now the project has a reference to be used for new contributors. Very good start!

**Comment by gronke** [comment]
Of course we need to update our documentation frequently, but https://github.com/iocage/libiocage/commit/27f24218ce551006e2ba5e44491df812de832348 is a good start that improved the docs. IMO we're pretty clear on the build steps too - it's all defined in `.travis.yml`.
