### ISSUE TITLE
add ability to select which columns to list

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#12]
currently, iocage list has a number of different formats `--long`, and `--quick` (and… well, default…)

i propose to simply add `--column X,Y,Z` or else, the same way `openstack server list` does it: `-c x -c y -c z`, so users (or completion scripts!) can slice exactly the information that they need.

**Comment by gronke** [comment]
https://github.com/iocage/libiocage/blob/6068a5c4ec7c4c2e7fdacaad8740e7f2d27cc3e3/libiocage/cli/list.py#L52

**Comment by igalic** [comment]
haah! thanks 😀

**Comment by igalic** [comment]
relatedly, from IRC:

```irc
<gronke> I want list json output :D
<meena> --libxo=
<meena> please, add that to the issue i opened.
<meena> i dunno how i forgot about that ~_~
<meena> hrm… there's no libxo for python ☹
<meena> so, does that mean we need someone to write a cython wrapper?
```
