### ISSUE TITLE
iocage_legacy points to wrong defaults config

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#127]
The defaults file created by iocage_legacy (master) is `/iocage/.defaults`.  Our current default location mistakenly points to `defaults` (not `.defaults`).

**Comment by urosgruber** [comment]
Found this 

https://github.com/iocage/iocage_legacy/blob/7c712bda3ca1cfd9b5d93dbe57efa75fc1c54c1b/lib/ioc-zfs#L1018

Not sure this is used by latest legacy anymore?

**Comment by gronke** [comment]
Outch, okay we need to patch that upstream. Different versions of iocage should never destroy each others settings! This is relevant for https://github.com/iocage/libiocage/issues/68#issuecomment-345838924 as well.

**Comment by urosgruber** [comment]
I found that the issue for .defaults and previously logs dataset was at

https://github.com/iocage/iocage_legacy/blob/7c712bda3ca1cfd9b5d93dbe57efa75fc1c54c1b/lib/ioc-info#L69

adding `|.defaults` fix the issue with iocage_legacy

**Comment by gronke** [comment]
... and here https://github.com/iocage/iocage_legacy/blob/7c712bda3ca1cfd9b5d93dbe57efa75fc1c54c1b/lib/ioc-common#L39-L41

**Comment by gronke** [comment]
Fixed in https://github.com/iocage/libiocage/commit/2c58be2b6b66885ffe812ba08f75dc7f4abb475b

**Comment by gronke** [comment]
@urosgruber the directory is now excluded from iocage_legacy as well. See https://github.com/iocage/iocage_legacy/pull/373
