### ISSUE TITLE
FreeBSD CURRENT release no longer available

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#129]
With switching the default FreeBSD mirror url to https://download.freebsd.org the `CURRENT` release is not available to fetch any longer.

**Comment by igalic** [comment]
IME, this is a bug on FreeBSD's side, not ours, and we should raise an issue with them.

This [bug] here is just for our own tracking / documentation.

**Comment by gronke** [comment]
Afaik this was supported in older iocage releases, so I would consider it a bug. Still, there are problems related to running jails on a release newer than the host, which is likely when tracking a development branch.

**Comment by foo2342** [comment]
This has been mitigated by offering support for custom releases. A user running -CURRENT should be able to install world manually.

**Comment by gronke** [comment]
fixed in #137 

Thanks @foo2342
