### ISSUE TITLE
Validation for `list`'s `output`

### ISSUE THREAD

**Issue by skarekrow** [iocage/libiocage#13]
We need it ;)

https://github.com/iocage/libiocage/blob/6068a5c4ec7c4c2e7fdacaad8740e7f2d27cc3e3/libiocage/cli/list.py#L77

**Comment by skarekrow** [comment]
Actually, JailConfig handles that. Nevermind!

**Comment by igalic** [comment]
i love when an issue is so quickly resolved ;)

**Comment by skarekrow** [comment]
lol..
