### ISSUE TITLE
Opt-In Cron Service

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#132]
The default status of the cron-service in a release rc.conf should be disabled. Users can manually enable it in Jails where the daemon is needed.

**Comment by foo2342** [comment]
IMHO we should not disable cron by default, since services may depend on it. 
Load spiked can be mitigated by giving default crons a random offset.

**Comment by gronke** [comment]
@foo2342 Sounds reasonable - cron can still be manually disabled in jails. We'll stick with the current, cron opt-out.

**Comment by igalic** [comment]
> some services may depend on it

that's a lot of qualifiers 😹

anyway, my main issue isn't spikes, it's that there's an unnecessary service running in a hundred jails, that's used in two.

and then, there's the issue that i don't know how to create a jail where by default, cron isn't running. is this even possible?

**Comment by gronke** [comment]
Iocages current default is running cron, so we should do the same by default. We already have a wrapper class for RCConf files. It's super easy to make the setting user accessible. :-)

**Comment by igalic** [comment]
aaahhhhhhhhh i see.
