### ISSUE TITLE
ask before deleting data

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#146]
There should be a dialog listing the the deletion targets. CLI commands should either ask for confirmation or accept a `-y` flag set being set on the command.

#### with dialog
```
# ioc destroy "foo*"
This jails will be deleted:
  - foo2
  - foo-bar
  - foobar
Are you sure? (y/N)
```

#### with flag
```
# ioc destroy "foo*" -y
```

**Comment by igalic** [comment]
for consistency's sake, the flag should be `-f`
