### ISSUE TITLE
inherit login.conf from host system

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#170]
It is annoying to manually configure the locale in each jail individually. IMO the default should be to copy `/etc/login.conf` from the host and adding an opt-out option to the config.

**Comment by foo2342** [comment]
I‘d change as little as possible in jails.
If a user want’s to change the login.conf, there are templates for that.

**Comment by gronke** [comment]
What is a better way to deploy the locale configuration to a jail? We do not support merging multiple templates (yet), which makes the suggestion only work when dismissing other features for this.

**Comment by igalic** [comment]
as always, i <something about templates>.

**Comment by gronke** [comment]
@igalic @foo2342 what do you suggest to do? We could go one step further and read the charset from the hosts login.conf and apply it to the jail. At the same time we could allow the user to manually override it with a jail config property.

**Comment by gronke** [comment]
(Closed because the behavior can be achieved with a template.)
