### ISSUE TITLE
py-libzfs HardenedBSD package not available

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#178]
The package py36-libzfs is currently unavailable in HardenedBSD 11. No other packages get installed, which breaks our install process via `make install`.

```
pkg: No packages available to install matching 'py36-libzfs' have been found in the repositories
```

Probably this is caused by a failing build. When checking out https://github.com/freenas/py-libzfs manually, setting the `EXPERIMENTAL` env helps compiling:

```sh
export EXPERIMENTAL=true
pip3.6 install -e .
```

respectively

```sh
setenv EXPERIMENTAL true
pip3.6 install -e .
```

**Comment by igalic** [comment]
is there a reference issue upstream?

**Comment by gronke** [comment]
Currently there are no issues. Kudos to https://github.com/orgs/freenas/people
