### ISSUE TITLE
CLI: import/export

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#208]
- Export jails to archive
- Import jails from archive

**Comment by igalic** [comment]
we could even consider implementing something like [pantahub](https://www.pantahub.com/) for sharing (at least with oneself;) pre-configured jails

now, i'm not saying i want docker hub, but,,,

**Comment by gronke** [comment]
Some thoughts about importing/exporting jails:
- An export must be independent of a release. This means a jail that was cloned from a template or release must be promoted in order to be fully recoverable without also exporting its origin.
- There can be other datasets in a jails dataset next to `root` or even nested inside. All of them must be included in the backup.
- It would be nice to have incremental exports, so that the feature can be used to keep multiple hosts in sync.
- When moving n jails from host A to B, the space occupied by the imported jails on host B should not be larger than it was on Host A. (Release data should not be included)
- Optionally the export should contain **all** data (not only the diff against the release or origin) to create backups that are unrelated to iocage at all.
- Exports from other iocage variants should be importable with libiocage
- The output of an export is always a single file in form of an archive file with selectable compression algorithm
