### ISSUE TITLE
remove (or imlement) pkg create's pkglist option

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#221]
currently `ioc create` has a `--pkglist` option that's not implemented, so we should either implement it, or remove it.

**Comment by gronke** [comment]
In my opinion this option should be removed because it can be achieved with a jail exec. Reading the documentation of previous versions this feature seems to be very specific in dealing with JSON files. Can't see the purpose of it.

**Comment by igalic** [comment]
```
pkg -J $(ioc get identifier <jailname>) install -y <pkgs…>
```

is easy enough, and it also means we don't have to "setup" pkg in each jail.

we should document it.
