### ISSUE TITLE
 remove (or imlement) pkg create's --empty option

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#222]
currently `ioc create` has a `--empty` option that's not implemented, so we should either implement it, or remove it.

**Comment by foo2342** [comment]
Super useful option for messing around with -current, please implement it.

**Comment by gronke** [comment]
I agree with you, we want this feature! Users starting with an empty root dataset may still activate basejail mounts at a later time.

**Comment by gronke** [comment]
Users can achieve the same with an `ioc exec -f <JAIL> pkg install -y <PACKAGES>`.
