### ISSUE TITLE
origin template is not stored anywhere

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#234]
when creating a new jail from a template,

```
ioc create --template php-backend --name cyhr
```

we get a message:

```
cyhr successfully created from php-backend!
```

but there's no evidence of that in its properties:

```
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_raw_sockets:0
allow_set_hostname:1
allow_socket_af:0
allow_sysvipc:0
basejail:no
basejail_type:None
boot:no
children_max:0
clonejail:no
defaultrouter:-
defaultrouter6:-
devfs_ruleset:4
enforce_statfs:2
exec_clean:1
exec_fib:1
exec_poststart:/usr/bin/true
exec_poststop:/usr/bin/true
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_timeout:60
host_domainname:-
id:cyhr
interfaces:
ip4:new
ip4_addr:vtnet0|172.16.0.13/12
ip4_saddrsel:1
ip6:new
ip6_addr:
ip6_saddrsel:1
jail_zfs:no
legacy:no
mac_prefix:02ff60
mount_devfs:1
mount_fdescfs:1
mount_procfs:0
priority:0
release:11.1-RELEASE
resolver:-
rlimits:-
securelevel:2
stop_timeout:30
sysvmsg:new
sysvsem:new
sysvshm:new
tags:-
template:no
vnet:no
```

**Comment by gronke** [comment]
```
zfs get origin tank/iocage/jails cyhr
```

**Comment by igalic** [comment]
the main reason for having this is so that my systems can know which jails to rebuild if (when) a template was rebuilt.

This indirection makes establishing that pretty tricky, as there is no directly discoverable relation (something that was the case in pyiocage, btw)

now, i understand (some) of the reasoning: we're storing an arbitrary string in our jails' config.json, and that string would need updating in case of renames.

again, something that, somewhere in between iocage versions consistently didn't matter, thanks to uuids :D 

we currently have no Unique ID per jail / template, an ID that stays stable across renames and rebuilds and restarts. perhaps such a thing is needed?

```json
{
  "name": "cowboy",
  "id": "3166dc4e-72dd-4c0f-bc05-b06ca9174e5a",
  "release": "33846256-d629-4a0c-8235-6b7f296f240b",
}
```

n.b.: We may similarly want a `version` attached to (at least templates & releases), so that systems which ***don't track state*** can figure out if our jail is drifting from its template/release:

```json
{
   "release": { "33846256-d629-4a0c-8235-6b7f296f240b": "2017.11.30.16.57" },
   "template": { "3166dc4e-72dd-4c0f-bc05-b06ca9174e5a": "2017.11.30.17.57" }
}
```

this would shift the onus of resolving the correct template name on the user of these fields, but at the very least they would exist and we can build a tree (graph?) of information about the system

**Comment by gronke** [comment]
The template feature of libiocage is applied at creation time. Instead of cloning the root dataset of a release the templates root dataset is used as clone origin. There is no way of updating a jail by updating its template. Templates are meant as an optimization for jail creation of similar type (e.g. a webserver is pre-installed and jail just needs to be started after creation). When you update a template, the next jail created receives the update - no existing one does.

I've checked if UnionFS could be an option, but found too many issues with it. The approach that looks the most promising for diffing the changes between a jail/template and its release is `rsync --compare-dest`. (libiocage already depends on rsync for basejail updates)

**Comment by igalic** [comment]
> There is no way of updating a jail by updating its template.

that's not (even almost ;) what i said:

> the main reason for having this is so that my systems can know which jails to rebuild if (when) a template was rebuilt.

basically, right now, we're allowing users to create dependencies which they themselves must track

**Comment by gronke** [comment]
> basically, right now, we're allowing users to create dependencies which they themselves must track

Templates can be used to speed up prior build steps. This mechanism should be rather embedded in iocage than being done manually by the user. Anyhow, if users want to track the dependencies, arbitrary config options can be used at any time. (Other iocage versions will ignore them, but they can be read/written with libiocage). An example:

```
ioc create -t my-template -b -n my-jail template_name=my-template
```
