### ISSUE TITLE
merge ioc create's --release and --template flag

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#255]
From a user's perspective the difference of `-r` & `-t` is *very* minimal.

A template is something i create by… some procedure.
A release is something i create by downloading it.

To be slightly more concrete, let's not say *something* but instead, *parent*

```
# i'm not sure about this change (`--release` vs `--name`)
ioc fetch --name 11.1-RELEASE

# create template `cowboy` from parent `11.1-RELEASE`
ioc create --name cowboy --parent 11.1-RELEASE
ioc start cowboy
ioc exec cowboy 'env ASSUME_ALWAYS_YES=YES pkg bootstrap'
ioc exec cowboy 'pkg install -y erlang elixir'
ioc stop cowboy
ioc set template=yes cowboy

ioc create --name web-be --parent cowboy boot=yes start=yes
```

----

related issues:
- #233 (ioc cli parameters are very inconsistent)
- #221 (remove or implement ioc create's pkglist parameter)

**Comment by skarekrow** [comment]
I like the suggestion! I also think the template and release flags should map to this as well for backwards compatibility with the current iocage (as all cli interface changes should)

**Comment by igalic** [comment]
given the differences between templates & releases, i think we should close this
