### ISSUE TITLE
move iocage.lib.helpers.exec() to Host class

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#258]
Now that we have multiple functions called `exec()`my first thought was to rename `iocage.lib.helpers.exec()` to  `iocage.lib.helpers.host_exec()` since this is where it's used.

however, it would probably me more consistent to move it to the Host class.

**Comment by gronke** [comment]
I'm in favor of moving the function to Host. It will be self explaining to use it on this object that commands are executed on the host.

**Comment by gronke** [comment]
After further looking into this I came to the conclusion that although some commands may become executed in a jail, the call forks jexec on the host. It does not make too much sense to require the full host to be loaded for command execution. Instead we should consider every execution of external commands as bad and replace them with better API.
