### ISSUE TITLE
Feature: Default config

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#26]
Currently libiocage has hardcoded default config properties. In iocage it should be possible to define global defaults by executing `iocage set foo=bar default`.

By providing a full list of defaults, each jails configuration only needs to contain the delta. When initializing the defaults, the global defaults should be read and override the hardcoded ones.

Even though it does not have influence on the way user defined globals work, it seems cleaner to export the hardcoded values to a json file instead as well.

**Comment by skarekrow** [comment]
This currently exists in iocage, I would suggest that we use the defaults as a base, and have the jails use a differential configuration on top of that. Instead of using it as a seed, like the current implementation in iocage does.
