### ISSUE TITLE
Warn user when a jail update failed because no release updates were fetched

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#270]
When the updates of the release are not fetched, jails using it fail to update.

Users should be informed about this, so that they know how to resolve the issue.

**Comment by gronke** [comment]
Not yet. We can do an early check if release update assets are available locally. Mounting `/var/www/freebsd-update` would fail as long as the source directory does not exist.

**Comment by igalic** [comment]
or in `/usr/freebsd-dist`
