### ISSUE TITLE
Multi-Pool Support

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#285]
iocage should support managing multiple data sources. The simplest form would be to activate multiple ZFS pools at once. Looking forward to run iocage itself in jails, we require to specify iocage root datasets rather than zpools where we expect an `iocage` dataset on top-level.

The current mechanism of iocage to detect an active pool by iterating over the available pools on the system and looking for the first one with `org.freebsd.ioc:active` property set should remain unchanged. Instead users can specify the datasources in their /etc/rc.conf:

```
ioc_dataset_pool0="zroot/iocage"
ioc_dataset_mypool="tank/some-dataset/iocage"
```

The entries above declare two ZFS data sources for iocage aliased `pool0` and `mypool`.

Having multiple active iocage data souces introduces the problem of conflicting jail or release names. Therefore the edge case behavior must be defined.

### Conflicting jail names
Whenever two jails with the same name appear on active datasources users may decide which pool they ment. If no data source was specified, the top one from the rc.conf file should be selected.

### Moving jails between pools
When a jail should be moved to another pool, import/export logic is required because the current mechanism (ZFS rename) does not work.

### NullFS-Basejail releases from a different data source
Jails may specify what source their release is mounted from. Although the initial jail creation is slower when storing it on a different source, there is no reason not to mount the basejail folders from a different data source than the jail is stored on.

Of course doing so requires both datasets to be available during jail runtime.

**Comment by igalic** [comment]
re moving jails between pools: if we had a daemon, we might want to provide a rebalacing service that can be parametriszed?

**Comment by shivno** [comment]
really nice features but i have the fear that this could get error-prone. what about starting easy first without moving and basejails from other data sources?

**Comment by gronke** [comment]
> if we had a daemon, we might want to provide a rebalacing service that can be parametriszed?

@igalic this library is supposed to be working state-less. Building a daemon will require some tweaks to deal with state monitoring/updating. Rather than putting a daemon in this project, I'd prefer to have another repository doing exactly that.

> really nice features but i have the fear that this could get error-prone. what about starting easy first without moving and basejails from other data sources?

@shivno I'm most concerned about users. We will definitely need new CLI syntax and there's a chance to screw it up. I'm experimenting with different concepts at the moment to build a prototype that we can then play with.
