### ISSUE TITLE
Single command execution

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#311]
When a jail is supposed to execute a single command and passthrough stdout and stderr we should omit the `persist` flag of the jail launch command and provide the command to execute as `command`. Optionally the jails `exec.start` services may not be passed as well.

The jail will stop immediately after command execution.

**Comment by igalic** [comment]
Can you describe the use-case for this feature?

are these jails that exist longer than just for the command-execution?
because, say, they are off-line at the time, and need an upgrade, or similar?
or is this to execute a single (untrusted) task?
