### ISSUE TITLE
ioc fstab rm does not unmount

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#346]
if a jail is running and i issue:

```
ioc fstab rm /root foo
```

then shutdown or or reboot the jail
that bind-mount will not be removed until i either do it manually, or reboot the host.

`ioc fstab show foo` will show it's gone, of course, but since `ioc fstab rm` did not umount it, it's still there.

**Comment by igalic** [comment]
didn't we fix this as a side-effect in #349 ?

**Comment by gronke** [comment]
No, not yet. We need to prevent setting properties on running jails in first place and can then extend libiocages capabilities to apply changes to running jails. There is no technical obstacle that prevents us from doing that.

**Comment by gronke** [comment]
At the moment this is unsupported. In some cases the teardown is running additional steps when a setting becomes enabled. This can cause trouble stopping the jail, so that the safest way is to inform the user about this constraint when attempting to alter a running jail.

**Comment by igalic** [comment]
i'm glad we opted for Hotplugging instead :tada: #466 :sparkles:
