### ISSUE TITLE
all CLI commands should catch 

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#358]
running `ioc fetch` without previously running `ioc activate` results in a trace ending in `iocage.lib.errors.IocageNotActivated`

we should catch this in *all* ioc cli commands — to be… user-friendly.

**Comment by gronke** [comment]
We can establish this check in the CLI on global level and remove the code from fetch (or other commands that would catch it). This is an internal error, so any time iocage attempts to access a pool it would occur. Eventually no changes are required.

**Comment by gronke** [comment]
implemented in #384
