### ISSUE TITLE
consider validating ip4 / ip6 addresses on set

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#371]
currently when creating a jail, we can currently create it with a perfectly invalid IP:

```
# ioc create --basejail --name tpl-web ip4_addr="vtnet0|.2/16"
tpl-web successfully created from 11.1-RELEASE!
```

only on start can we see that something may be off:

```
# ioc start tpl-web
[-] JailLaunch@tpl-web: FAILED [0.135s]: 2
Launching jail tpl-web failed
*** Error code 1
```

but not quite what.

we may want to validate this.

**Comment by igalic** [comment]
like how *cough* #113 *cough* i thought the [pathlib module](https://docs.python.org/3/library/pathlib.html) seems interesting…

**Comment by gronke** [comment]
True, both are pretty much made for those tasks. PRs welcome 👍
