### ISSUE TITLE
inconsistency between template=no and template=no,- usage

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#377]
in 8b1fea9b06b44cdedc813c949e7d51176b5906cd @gronke introduced a fix for iocage_legacy flavours which use `template=none` instead of `template=no`

However, many parts of the code still only assume `template=no` when dealing with jails

This should be fixed.

**Comment by gronke** [comment]
The internal storage jail.config.data should always contain a Boolean value. The output to ZFS can be a mapping `False => None`.
