### ISSUE TITLE
Bug: Do not **unintentionally** modify function arguments

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#38]
We have a handful of functions that take non-`None` arguments, and then modify them.
This leads to python directly modifying the passed argument, and is generally considered bad form.

One such example is `JailConfigAddresses#add()`

```python
    def add(self, nic, addresses=[], notify=True):

        if isinstance(addresses, str):
            addresses = [addresses]
```

maybe there are linter params that will warn us of such code, until then we might need human eyes.

**Comment by gronke** [comment]
Agreed. Needs to be addressed! Should not be too complicated to fix, but a bit hard to spot. Is there a static code analyzer that does check for it?

**Comment by igalic** [comment]
i don't know…
it doesn't seem to be in pylint, https://pylint.readthedocs.io/en/latest/technical_reference/extensions.html
and we already use flake8, which dosen't seem to catch those either: http://flake8.pycqa.org/en/latest/user/error-codes.html

**Comment by igalic** [comment]
after installing `flake8-mutable`, i get the following:

```./iocage/lib/Network.py:35:33: M511 - mutable default arg of type List
./iocage/lib/Network.py:36:33: M511 - mutable default arg of type List
./iocage/lib/DevfsRules.py:33:47: M511 - mutable default arg of type List
./iocage/lib/Jail.py:186:63: M511 - mutable default arg of type Dict
./iocage/lib/Filter.py:46:36: M511 - mutable default arg of type Call
./iocage/lib/NetworkInterface.py:34:33: M511 - mutable default arg of type List
./iocage/lib/NetworkInterface.py:35:33: M511 - mutable default arg of type List
./iocage/lib/NetworkInterface.py:43:33: M511 - mutable default arg of type List
```
