### ISSUE TITLE
Use type-hints for all function arguments & return values

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#39]
Since we're already using Python 3.6, we should consider also specifying all our input parameters with input & return types.

**Comment by gronke** [comment]
[pep-3107](PEP 3107 -- Function Annotations)

**Comment by igalic** [comment]
oh, interesting! i thought (PEP 484 -- Type Hints)[https://www.python.org/dev/peps/pep-0484/) was all we needed

**Comment by gronke** [comment]
Same syntax! Let's do it.

**Comment by skarekrow** [comment]
They work in concert :D and yay yes this was on my table for "eventually", very happy to see this being worked on 👍

**Comment by igalic** [comment]
how about formally extending `CONTRIBUTING.md` with #42, to say that no functions are to be added without a type signature?

**Comment by skarekrow** [comment]
https://github.com/iocage/libiocage/commit/ba62e1fb45bd3ce8b5907c287833eec405e24aa3 done

**Comment by igalic** [comment]
💜

**Comment by araujobsd** [comment]
The first goal of mypy was to be an alternative to Python language, something like pypy but with different purpose. The main design wasn't to be a test tool! ;)

I would discourage you to use it, it will add more complexity to the project as well as additional confusion.
Also, I can't see a real benefit of it, and plus it is an experimental project.

Stick with pure python is the right thing to do, force contributors to implement something that is not standard in the market is just a big "no go".

I would revert this commit too: https://github.com/iocage/libiocage/commit/ba62e1fb45bd3ce8b5907c287833eec405e24aa3

**Comment by igalic** [comment]
i thought that part of the reason for choosing python 3.6 was so that the project could make full use of the new language features, including types. mypy is a crutch here, and i would rather revert adding that, than adding types

**Comment by araujobsd** [comment]
You can do full use of Python 3.6; but, include an external dependency that is in experimental stage, doesn't sounds good for several reasons: maintainability, interdependence, stability and plus I can't see what improvements it can bring to the project, but it only adds more complexity.

For me it is not clear what problem you are trying to solve here using mypy. So, I'm totally against to include mypy in this project, if there is not a technical debt or a serious problem to be solved.

**Comment by igalic** [comment]
a first big slew, or rather, the ground-work! has now been laid with the merging of #54.
Thanks to everyone who's helped out here — in particular, @gronke, who did a lot of debugging with me.

***You*** too can help out with this issue! take a look at `mypy --strict libiocage/` and choosing, and following a thread. start adding types, validate with `mypy libiocage` until it comes back clean.

**Comment by gronke** [comment]
Strong typing is established in the entire library.
