### ISSUE TITLE
extend list to retrieve be able to return all information

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#414]
currently, `ioc list` is our most powerful tool to extract information from all jails, templates and releases. Best of all it comes with an output format that everyone can deal with: JSON.

however, it requires one thing: prior knowledge. Unlike `get`, which can return `all` properties, in `list` we need to know exactly what we're asking for, which in turn means duplicating knowledge in multiple tools

`get` like many others (#233) lacks an JSON output format option (#232, #231)
but our problems are a bit deeper than that: the global namespace of properties is polluted (#413).

******

So here's some improvements we can make to libiocage, to make it easier to use from  third-party tools — especially those written in not-Python:

- implement namespaces for properties #413 
- add a --verbose option to list, which outputs *all* properties

**Comment by gronke** [comment]
I suggest to write a tiny helper using the library to achieve output for scripting usage:

```python3
import iocage
import json

jail = iocage.Jail("myjail")

data = {}
for key in jail.host.defaults.config.keys():
  data[key] = jail.config[key]

print(json.dumps(data))
```
