### ISSUE TITLE
Names for creation of a number of jails

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#44]
When creating a number of jails with `--count` flag, names cannot be set, because the second creation attempt will fail because the jail with this name already exists.

It is required to introduce a wildcard character that represents the index of the currently created jail.

My suggestion is: `ioc create --count 128 --name "my-%i-jail-of-%n"` where `i` is the index and `n` is the total number of jails to create.

**Comment by rwestlund** [comment]
I never understood why this is a feature to begin with.  Why not just let people do this?
```sh
for i in $(seq $num); do iocage create -n "$i-of-$num"; done
```
No need for iocage to reinvent the wheel.

**Comment by skarekrow** [comment]
I used it for benchmarking and debugging purposes. I never really intended users to use it much, but it has it's niche use cases.

**Comment by gronke** [comment]
I agree with @rwestlund. Why should we re-invent shell or Python. We already have excellent tools to do the job. Will remove the `--count` flag from the cli command entirely.
