### ISSUE TITLE
No access to IOCAGE_* env variables from start hook

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#480]
@urosgruber [has reported](https://github.com/iocage/libiocage/pull/344#issuecomment-415859736) a regression that no env variables prefixed with `IOCAGE_` are available in the jail exec_start hook.

**Comment by gronke** [comment]
Thanks for reporting the issue @urosgruber. I'm now investigating when the regression was introduced.

**Comment by urosgruber** [comment]
@gronke I was reviewing launch-scripts folder right now and it's quite magical :) I'm guessing it's better to not touch anything there, right?

**Comment by gronke** [comment]
The files in there are created on start/stop. So it would not help much to manually edit those.
