### ISSUE TITLE
Exec have issues if command uses -u 

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#491]
I'm not sure if it's just local issue with my configuration but it seems that running `ioc exec foobar ps -aux` will result in error "**su: unknown login x**" 

I tried couple of commands where `-u` is used and always the same problem. Issue is also if I use `ioc exec -f foobar`

**Comment by gronke** [comment]
@urosgruber you can put the command in quotes like

```
ioc exec foobar "ps -aux"
```

otherwise you can signify the end of command options with a double dash `--`

```
ioc exec foobar -- ps -aus
```

**Comment by urosgruber** [comment]
@gronke I tried with double quotes and the error was even more weird "**jexec: execvp: ps -aux: No such file or directory**" But with `--` it does work as expected. Maybe something to put in docs or help?

**Comment by gronke** [comment]
@urosgruber done. `ioc exec --help` will now print appropriate hints.
