### ISSUE TITLE
Feature: Rename jail

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#52]
A jails name also defines the jails dataset location relative to the activated zpool. That's why it's important to do more than just renaming the property. Certainly we must force a jail to be stopped for renaming it.

### Requirements
- When renaming a Jail
  - [ ] an exception is raised when the jail is started
  - [ ] moves the dataset immediately
  - [ ] changes the `host_hostname` when it was manually set (available in config.data) and matches the old jail name

**Comment by igalic** [comment]
%s/when/if/g
