### ISSUE TITLE
pkg symmetry: pkg currently only installs

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#526]
currently, `ioc pkg` only allows installations

to uninstall a package we can either:

```sh
ioc exec jail01 -- pkg delete -y pkg-name
```

when the jail is running, XOR, if the jail is not running:

```sh
pkg -r /path/to/jails/jail01/root delete -y pkg-name
```

i believe we can offer a better interface, and more consistent interface.

**Comment by gronke** [comment]
I'd like to separate the concerns. At the current time a jail has to be stopped to install packages. This can be changed, but is another task than adding package removal.
