### ISSUE TITLE
Inter-Jail dependencies

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#529]
It would be nice to be able to reference other jails.

This could enhance for instance:
- Jail Boot Process
- Jail-to-Jail VNET connections or sockets
- Mountpoints from one Jail to another

**Comment by urosgruber** [comment]
That would be awesome feature. I handle connectivity feature between the jails from hook scripts atm. It works but if I could use some features that would simplify this I 👏 for this feature.

**Comment by gronke** [comment]
Let's start the discussion at the syntax and language level level: We need to find a way to point to another jail.

When doing so, one of the following things can happen:
1. A jail that was referenced was deleted, renamed or is temporary unavailable
2. On a different host, the other jail is unknown to the new host or needs to be imported in specific order. A lot of edge cases are created, that require being caught.

The jail identifier that matches one jail is it's name (or UUID), so that the reference would have to rely on a string, that has the issues mentioned above.

## Solution: Nested Jails

I am unsure if the more elegant way to solve all this is the [Nested Jails](https://iocage.io/handbook/features/nested-jails/) feature. Would be nice find scenarios where Nested Jails do not solve the task properly.

### Jail Boot Process
The iocage running in the outer Jail can start its dependants using the service and boot priorities.

### Jail-to-Jail VNET connections or sockets
The inner Jail can be assigned to a bridge that the outer Jail provides.

### Mountpoints from one Jail to another
The file system structure(s) to be shared across jails are created in datasets within the outer Jail. The data is mounted into consuming jails from an absolute path from within the outer Jail.

**Comment by igalic** [comment]
> ### Mountpoints from one Jail to another
>
> The file system structure(s) to be shared across jails are created in datasets within the outer Jail. The data is mounted into consuming jails from an absolute path from within the outer Jail.

i really like this idea, cuz it means you can structure your jails into a build process and a serving daemon, which are often vastly different stacks

**Comment by gronke** [comment]
I'm closing this now as solved. May the person who finds their use-case being impossible to achieve with Nested Jails speak up and re-open the Issue.
