### ISSUE TITLE
launch-scripts/start.sh sources /.iocage/.env twice

### ISSUE THREAD

**Issue by igalic** [iocage/libiocage#549]
Here's mine:

```sh
#!/bin/sh
. /.iocage/.env
. /.iocage/.env
/sbin/ifconfig vnet0:$IOCAGE_JID:j link 02:ff:60:db:c9:16 mtu 1500 name vnet0 up > /dev/null
/sbin/dhclient vnet0 > /dev/null
/sbin/ifconfig lo0 localhost
/bin/sh /etc/rc
```

**Comment by gronke** [comment]
Although this is invalid behavior, I've labled this Issue as "chore" because it has no effect on jail execution.

**Comment by igalic** [comment]
i think it's only happening when we enable vnet:

https://github.com/iocage/libiocage/blob/1427afa11762df9869cfffe0f44b52b4f84ce9ea/iocage/Jail.py#L474-L491
