### ISSUE TITLE
Destroy selects jails from main iocage dataset

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#569]
When selecting a jail with it's full identifier `two/foo`, libiocage will still target a jail with the same name on the main dataset instead if it exists:

```console
$ sysrc ioc_dataset_one="zroot/iocage1"
$ sysrc ioc_dataset_two="zroot/iocage2"
$ ioc create one/foo
$ ioc create two/foo
$ ioc destroy two/foo
These jails will be deleted
  - one/foo
Are you sure? [y/N]:
```

**Comment by igalic** [comment]
is this

> ```sh-session
>  $ sysrc ioc_dataset_one="zroot/iocage1"
>  $ sysrc ioc_dataset_two="zroot/iocage1"
>  ```

a typo?
both of them are pointing at the same zfs dataset
