### ISSUE TITLE
ioc start does not work for basejail and have issues with clonejail

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#69]
- [x] Supply `iocage --version`
latest master **ioc, version 0.2.11 08/29/2017**

Using `ioc start UUID` on basejail type of legacy jail just return with no info also jail is not running. Using same command on clonejail type starts the jail but with some errors

```
Command exited with 1: /usr/sbin/jexec ioc-9048b2dc-91ac-11e7-b8c6-7071bca7c826 /bin/sh /etc/rc
    jexec: execvp: /bin/sh: No such file or directory
Command exited with 1
```
I managed to get it work for a while but I was unable to replicate fully working start with latest master.

**Comment by gronke** [comment]
I have seen this error message before when mounting or cloning the base dataset(s) failed. This is a bug and will be addressed with one of the next Pull-Requests!

**Comment by urosgruber** [comment]
Not sure what was changed but `ioc start UUID` on jails created by legacy iocage does nothing with message "No jails started your input". I guess this is ok and intentional? On that note I think this ticket can be closed.

**Comment by gronke** [comment]
You should be able to manipulate existing iocage legacy jails. Have you tried using the short name (the first block from the UUID)?

**Comment by urosgruber** [comment]
Yes I tried with short name, tag name and does not make any difference. FYI the other way around works. So I can start and stop jail created by ioc with legacy iocage.

**Comment by urosgruber** [comment]
Here is debug output if it helps.

```
Updated /etc/rc.conf data from /iocage/jails/d8cf14ee-2c22-11e8-8d77-7071bca7c826/root/etc/rc.conf
Updated /etc/rc.conf data from /iocage/jails/d8cf14ee-2c22-11e8-8d77-7071bca7c826/root/etc/rc.conf
Updated /etc/rc.conf data from /iocage/jails/d8cf14ee-2c22-11e8-8d77-7071bca7c826/root/etc/rc.conf
No jails started your input:
```

**Comment by gronke** [comment]
I could reproduce this issue. Will have a look asap :)

**Comment by gronke** [comment]
@urosgruber I'm curious if https://github.com/iocage/libiocage/pull/273 fixes your problem.

**Comment by urosgruber** [comment]
@gronke I think your fix did the trick. It works fine now. Thanks for a quick turnout.
