### ISSUE TITLE
Feature: support for resolving runtime variables [$50]

### ISSUE THREAD

**Issue by urosgruber** [iocage/libiocage#70]
As discussed through IRC adding option to use variables on specific attributes that are resolved on runtime would make using exec.pre/post_start/stop a lot easier. Native jail with jail.conf supports this out of the box ([jail.conf](https://www.freebsd.org/cgi/man.cgi?query=jail.conf&apropos=0&sektion=5&manpath=FreeBSD+11.1-RELEASE+and+Ports&arch=default&format=html), but I think it's not possible via cmd line using `jail -c ...` 

A workaround I did on legacy jail was to add jail name while calling exec scripts https://github.com/urosgruber/iocage/commit/ca766a772d1468b32d10a99888efe49a748e72e3

Example of an old script we used post_start script that is using jail name as an argument but could  be improved by providing JID or some other parameter 

```
#!/bin/sh

# get current jid
_jid=`jls -j $1 jid 2>/dev/null`
_ip=`jls -j $1 ip4.addr 2>/dev/null`
_name=$1

# cpuset
# cpuset -c -l 0 -j ${_jid}

# mem limit
rctl -a jail:$1:memoryuse:deny=256M

# pf
( pfctl -a jails -sr ; echo "pass on lo0 from ${_ip} to ${_ip}" ) | pfctl -a jails -f -

# update started time and status
mysql -ss -D db -e "UPDATE service SET started=NOW(), status='running', jid=${_jid} WHERE name='$1';" 2> /dev/null
```
Similarly for post_stop script and pre_ scripts.

Nice to have would be to specify a folder **pre_start.d**  where all executable files would be executed with same parameters. example: `ioc set exec_prestart="/my/prestart.d/ ${jid}"`

**Comment by gronke** [comment]
Hey @urosgruber, does #82 look like what you've wanted? 😃

**Comment by urosgruber** [comment]
@gronke looks promising 👍 . Unfortunately I'm on my way to the airport and will be away until next Tuesday. So I will have trouble doing tests in my environment. 

One thing to note here (I noticed this bug with iocage_legacy) is to not pass this variables to the actual jail. I'm not sure why this happened even though `exec.clean=1` was set.

I can run some tests on Tuesday and let you know, ok?

**Comment by gronke** [comment]
> I can run some tests on Tuesday and let you know, ok?

Yes of course. If feedback on the PR tells me it's ready to merge, I will consider doing that, but it's simple to re-open the ticket after you've spotted missing things.

> One thing to note here (I noticed this bug with iocage_legacy) is to not pass this variables to the actual jail.

Indeed. Will look into that now!
