### ISSUE TITLE
Docs: Development Environment

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#74]
We introduced code checking with flake8 and mypy, but did not document how to configure and use the development environment.

At least developers need to know a list of dependencies and some helper to install them on FreeBSD and HardenedBSD.

- Makefile
  - [x] `make travis` runs the same tasks as they would on TravisCI
  - [ ] `make test` runs the code style checks and unit tests
  - [ ] `make dev-dependencies` installs developer dependencies (and general dependencies)
  - [x] `make install` installs libiocage to the system
- Readme
  - [ ] lists general iocage dependencies
  - [ ] lists iocage development dependencies
  - [ ] explains how to setup the development environment using `make dev-dependencies`

**Comment by igalic** [comment]
Travis is running: `make check` and `make check-deps` to install the deps needed for that

**Comment by gronke** [comment]
We simplified the Makefile and made (dev-) dependencies self-explaining.
