### ISSUE TITLE
Feature: Tags

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#75]
In addition to a resource name, jails may have one or more tags that makes them selectable.

The general functionality to provide tags is embedded in libiocage, but we need to expose the feature via the command line interface to make it usable.

For compatibility with previous versions the tags should be stored as comma separated string. Another thing to consider is the previously used jail `tag` configuration option which should be seamlessly merged into the tags when it exists.

### Requirements
- [x] a jail can have one or more tags
- [x] a jails tags can be shown in list command output
- [x] jail filters can match individual tags
- [x] jail config property `tags` can be set from a comma separated string
- [x] jail config property `tags` can be set from a list of strings 
- When no user defined `tags` property was found in a jail's configuration
  - [x] setting a `tag` JailConfig item sets the deprecated `tag` property
  - [x] setting `tags` removed any existing `tag` property from the configuration
- When user defined `tags` are already existing
  - [x] setting a `tag` that already exists in `tags` makes it the first item in `tags` 
  - [x] setting a `tag` that does not exist in `tags` yet, adds it as first item

**Comment by gronke** [comment]
**Updated requirements**

### Before
- A jail can have one or more tags
- A jails tags can be shown in list command output
- Jail filters can match individual tags
- When a jail has the `tag` property
  - The value is seamlessly merged into tags as first item
- When a jail has no `tag` property
  - The `tag` property resolves to the first item in `tags` or `None` instead

### After
- a jail can have one or more tags
- a jails tags can be shown in list command output
- jail filters can match individual tags
- jail config property `tags` can be set from a comma separated string
- jail config property `tags` can be set from a list of strings 
- When no user defined `tags` property was found in a jail's configuration
  - setting a `tag` JailConfig item sets the deprecated `tag` property
  - setting `tags` removed any existing `tag` property from the configuration
- When user defined `tags` are already existing
  - setting a `tag` that already exists in `tags` makes it the first item in `tags` 
  - setting a `tag` that does not exist in `tags` yet, adds it as first item

**Comment by urosgruber** [comment]
I think this would help as well in cases custom properties. Not ideal though but will be great improvement.
