### ISSUE TITLE
Use `--libxo=json` to parse jls output

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#8]
@igalic mentioned in a PR review that we should [consider using `--libxo=json`](https://github.com/iocage/libiocage/pull/5#discussion_r134399285) to get parsable output of jls.

Personally I would prefer to get the jail state from a python library, but until then the formatted output is a clean alternative to the way we currently parse the output.

**Comment by igalic** [comment]
we can probably generalize that, whenever we use an `exec` instead of a library.

**Comment by gronke** [comment]
Implemented.

@igalic btw. you can simply write "fixes #XYZ" in your PR description to automatically close referenced issues. https://help.github.com/articles/closing-issues-using-keywords/

**Comment by igalic** [comment]
yeah, but, fixes is a lie :P

**Comment by gronke** [comment]
haha

**Comment by skarekrow** [comment]
I think this can be closed as it was implemented. Reopen if I'm wrong :D
