### ISSUE TITLE
Check for optional return types

### ISSUE THREAD

**Issue by gronke** [iocage/libiocage#86]
As @igalic noted in https://github.com/iocage/libiocage/pull/83#discussion_r138437591 the library returns None in functions that do not return an optional type.

```python
def something() -> str:
    # ....
    return None
```

should be instead

```python
import typing
def something() -> typing.Optional[str]:
    # ...
    return None
```

**Comment by igalic** [comment]
i'm kinda upset that mypy isn't catching this

**Comment by igalic** [comment]
figured out the reason why mypy isn't catching this: we're not asking it to ;)

we could ask it with `--strict`, or `--strict-optional`, unfortunately, adding this option would make our tests very sad ;)

we could add it to our travis test-matrix with `allow_failure`

i have this reproduced & "fixed" here: https://gist.github.com/igalic/b9ab334a8093a35267fb3b77e0f5c09d/revisions

**Comment by gronke** [comment]
The simplest way to address this is to work on making `mypy --strict` pass.

**Comment by igalic** [comment]
"""""simplest""""" way, yes ;)

**Comment by gronke** [comment]
I did not say the easiest way! But the one we have to think the least about. Or did you give up on full typing coverage? 😏

**Comment by igalic** [comment]
i did not, it's just very tedious work
fortunately, it's very tedious work that ends up in important redesign (and/or bug fixes) cuz some of the assumptions we made where… shall we say, naïve.

**Comment by gronke** [comment]
Duplicate of #39
